# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libnetcdf-dev
      - netcdf-bin
